### ISSUE TITLE
Doesn't work with windows 10

### ISSUE THREAD

**Issue by kantagara** [hakuna-m/wubiuefi#8] opened 2016-05-15 10:42 UTC
Hello, I've successfully downloaded wubiuefi which downloaded the image and then i restarted my machine which succesfully entered in ubuntu to finish the installation... BUT afterwards there is no option to enter to Ubuntu... I'm using windows 10, I dunno what to do...

**Comment by hakuna-m** [comment] 2016-05-15 20:52
Wubi adds an menu entry to the boot menu which only boots one-time automatically because Wubi should be a safe way to install Ubuntu without a non bootable Windows. 

So after that you need to select it manually. I assume that your Windows 10 uses UEFI mode, so Wubi adds the menu entry to the UEFI menu. 

On some computers you can enter that menu by pressing `F12` immediately after switching on your computer. But it depends on your UEFI firmware (formerly BIOS) and your firmware settings. e.g. you should disable [Fast Boot](http://www.tenforums.com/tutorials/21284-fast-boot-enable-uefi-firmware-settings-windows-8-10-a.html) if you want to enter your UEFI menu by pressing function keys. Note: Wubiuefi only disables the Windows setting "Fast Startup" by default. 

If it is not possible to enter the UEFI menu or you just want to change the boot order, there are programs like [EasyUEFI](http://www.easyuefi.com/index-us.html) to manage your UEFI boot options.

**Comment by kantagara** [comment] 2016-05-19 09:13
Thanks for the reply. I've choosed ubuntu BUT it didn't get to the OS instead it gave me some boot error ( I can't remember what it is, but I googled it and it said that my partition is corrupt or something like that...)

**Comment by hakuna-m** [comment] 2016-05-19 14:15
> I can't remember what it is

Is the error message reproducible ?
Did you get the following message ?
```
It is not possible to boot from the Ubuntu image.
Please verify that the Ubuntu installation was not removed.
If that is not the case, please check that the Windows filesystem
is not corrupted: reboot into Windows and run: chkdsk /r
Then try again.
```
Or did you get a "BusyBox" prompt ?
Or did you get the following error message ?
```
Failed to partition the selected disk
No root file system is defined
```

**Comment by kantagara** [comment] 2016-05-19 15:37
It's the busybox error

**Comment by hakuna-m** [comment] 2016-05-19 22:00
If you choose Ubuntu again, does the following message still appear before busybox ? 
```
Completing the Ubuntu installation.
For more installation boot options, press `ESC' now...
```

**Comment by kantagara** [comment] 2016-05-21 12:35
No. I get GRUB then when I select ubuntu it leads me to busyBox

**Comment by hakuna-m** [comment] 2016-05-22 13:11
A remote diagnostics for BusyBox errors is a little bit difficult. But if the first boot into Ubuntu to complete the Ubuntu installation works, it should be repairable.

A most common reason in connection with Windows 10 is that Windows 10 does not shut down completely. In UEFI mode this should be fixed automatically by powercfg command. see [here](https://github.com/hakuna-m/wubiuefi/wiki#fast-startup-and-hibernate). But maybe your Windows 10 is not in UEFI mode, powercfg command fails or other programs reset that setting.

**Comment by kantagara** [comment] 2016-05-23 08:02
I was sure that powercfg was turrned of, but apperently it wasn't. The
problem is solved. Thanks!!

2016-05-22 15:11 GMT+02:00 hakuna matata <notifications@github.com>:

> A remote diagnostics for BusyBox errors is a little bit difficult. But if
> the first boot into Ubuntu to complete the Ubuntu installation works, it
> should be repairable.
>
> A most common reason in connection with Windows 10 is that Windows 10 does
> not shut down completely. In UEFI mode this should be fixed automatically
> by powercfg command. see here
> <https://github.com/hakuna-m/wubiuefi/wiki#fast-startup-and-hibernate>.
> But maybe your Windows 10 is not in UEFI mode, powercfg command fails or
> other programs reset that setting.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hakuna-m/wubiuefi/issues/8#issuecomment-220831668>
>



-- 
Nikola Garabandić

**Closed** 2016-05-23 19:31 UTC
Labels: help wanted

**Comment by AndroidDeveloperLB** [comment] 2016-09-24 22:50
Does this mean it can run like Wubi did, yet on Windows 10 ? 
If so , is there a bin version of this? One that I can just run without building?

**Comment by hakuna-m** [comment] 2016-09-25 14:38
@AndroidDeveloperLB 

> Does this mean it can run like Wubi did, yet on Windows 10 ?    

Yes, it can. But note, that if your Windows 10 is installed in UEFI mode, Wubiuefi uses a different boot menu (see [here](https://github.com/hakuna-m/wubiuefi/wiki#uefi) ) and probably Secure Boot is also enabled (see [here](https://github.com/hakuna-m/wubiuefi/wiki#secure-boot).

> If so , is there a bin version of this?

If you follow the links of the [releases overview](https://github.com/hakuna-m/wubiuefi/wiki#releases) or the [latest release link](https://github.com/hakuna-m/wubiuefi/releases/latest), you find an exe file below "Downloads".

**Comment by AndroidDeveloperLB** [comment] 2016-09-26 17:52
"installed in UEFI mode" ? How can i check this? What is this mode anyway? 
About the exe file, thank you. Please put it in the main page here too, to show where to install it for Windows users who don't wish to compile... :)

**Comment by hakuna-m** [comment] 2016-09-27 19:20
> "installed in UEFI mode" ?

If an operating system like Windows should use new [UEFI](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface) features, it is necessary that it installs an UEFI specific environment (e.g. an EFI boot loader, an EFI partition, ...).   

> How can i check this?

e.g. see [here](http://superuser.com/a/946884)

> Please put it in the main page here too, to show where to install it for Windows users who don't wish to compile... :)

There are some limitations in providing binary files on Github. As far as I know the standard way is to add it to [releases](https://github.com/hakuna-m/wubiuefi/releases). You find "releases" in the row beginning with "commits".

**Comment by AndroidDeveloperLB** [comment] 2016-09-28 08:15
I didn't mean to put the binary file on Github. I meant to put the link you've written there.
It would also be nice to put a link/explanation there about the check of UEFI you've mentioned now. 

Please do consider it.

**Comment by hakuna-m** [comment] 2016-09-29 20:04
@AndroidDeveloperLB 

> I meant to put the link you've written there.

The link is already in the main page of our [Wiki](https://github.com/hakuna-m/wubiuefi/wiki). The Wiki should the main page for users who don't wish to compile.

But maybe, you mean the [README](https://github.com/hakuna-m/wubiuefi/blob/master/README) file which is displayed at the bottom of the main page of the [Github repository](https://github.com/hakuna-m/wubiuefi). 

If you mean that, you are right. We should also add links of our Wubi Wiki. 

> It would also be nice to put a link/explanation there about the check of UEFI you've mentioned now. 

You are also right. We should add further information about UEFI. I'll try to include the information in the next days.
