### ISSUE TITLE
How to install pop os with wubi ??

### ISSUE THREAD

**Issue by cata0309** [hakuna-m/wubiuefi#126] opened 2019-02-04 23:04 UTC
I know there are some people that asked this in the past, but no proper answers. I really want it to be a dual boot with my Windows 10, I want to use both.
How can I do that ?

**Comment by hakuna-m** [comment] 2019-02-05 21:56
Duplicate of #83 and #108 

There is an untested support with [various distros/versions](https://github.com/hakuna-m/wubiuefi/wiki#various-distrosversions) feature.

For this feature you can download manually the ISO of your Ubuntu based distro (in your case Pop!_ OS) and Wubiuefi. see [Where can I download Wubiuefi ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-can-i-download-wubiuefi-) and [How can I use a pre-downloaded ISO file ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-)

Note: The feature is untested for Pop!_OS. As I wrote [here](https://github.com/hakuna-m/wubiuefi/issues/108#issuecomment-399355257), you can test it on your own risk and I can modify the Wubiuefi configuration if there is no matching environment.

But the matching environment is only the first step of the installation. If there are other issues  Pop!_OS with Wubiuefi is still unsupported.

**Closed** 2019-10-13 05:48 UTC
Labels: duplicate, question
