### ISSUE TITLE
Can't install Ubuntu 17.10 or Kubuntu 17.10 final with WubiUEFi Ubuntu 17.10 (rev 326)

### ISSUE THREAD

**Issue by darkgenius1987** [hakuna-m/wubiuefi#77] opened 2017-10-22 08:25 UTC
I tried to install Ubuntu or Kubuntu 17.10 final with Wubi UEFi but the instalation doesn't work, a message Selecting the target directory appears after i select drive and i choose a password to begin instalation, just like in this post: https://github.com/hakuna-m/wubiuefi/issues/68 . What can i do to be able to install Ubuntu or Kubuntu 17.10 final with Wubi?

**Comment by hakuna-m** [comment] 2017-10-22 13:59
> just like in this post: #68 

If the last line of your [log file](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-) is  
`DEBUG TaskList: ## Finished select_target_dir`
IMHO it is a duplicate of #68 . 

#68 was resolved by installing another Wubiuefi version. see [here](https://github.com/hakuna-m/wubiuefi/issues/68#issuecomment-328594294).

So IMHO, it should be helpful to [uninstall Wubiuefi](https://wiki.ubuntu.com/WubiGuide#Uninstallation) before installing it again. Note: If you run the same Wubiuefi version again, it runs also an uninstaller automatically. But the uninstaller is optimized. If the uninstaller knows that you want to install the same version again, it doesn't remove same parts. 

But the reason is still unclear. 

The issue has never been occured in our tests. So a special environment (Windows version, programs, configuration) seems to be necessary. 

There is no error message. So Wubiuefi waits for something. Maybe, if you wait a while a timeout error occurs which indicates the reason. Or [Windows Task Manager](https://en.wikipedia.org/wiki/Task_Manager_(Windows)) can show the tasks which are responsible for blocking Wubiuefi.

**Comment by AlekseySyryh** [comment] 2017-10-25 12:44
I understand reason of error, and also I found way to repoduce it and workaround to fix it. 
It depends on your system culture. If it is En-Us - everything works fine, but another culture are reproduces the error.

You should check that setting (sorry I do not have Windows with English GUI, but you will probably recognize it).
![fail](https://user-images.githubusercontent.com/10423839/31999043-5a642cee-b9ab-11e7-9d9c-2be6edeae5b0.png)
I thing changes of commit 7f499dca9a928397d6244381106129d9c35c0607 are leading to that error, but my skill is not good enough to fix it myself.

Anyaway temporary switching of culture to English (USA) will allow to bypass an error.

**Comment by hakuna-m** [comment] 2017-10-25 20:19
Thanks for your response. In the past, we tested it with different languages. But languages like German, French, Japanese,... do work. Because of your response, I tested it again with other languages like Polish and Russian. These language do not work. I try to fix the issue.

**Comment by hakuna-m** [comment] 2017-10-26 17:32
The issue has been resolved.

As I wrote in my previous post, I was able to reproduce the error by running wubi1710r326 from command prompt with
`wubi1710r326.exe --language pl_PL`
and
`wubi1710r326.exe --language ru_RU`

I also got some error messages within command prompt window.
```
Exception in thread tasklist:
Traceback (most recent call last):
  File "\lib\threading.py", line 801, in __bootstrap_inner
  File "\lib\wubi\backends\common\tasklist.py", line 393, in run
  File "\lib\wubi\backends\common\tasklist.py", line 212, in __call__
  File "\lib\wubi\backends\common\tasklist.py", line 335, in _run_subtasks
  File "\lib\wubi\backends\common\tasklist.py", line 213, in __call__
  File "\lib\wubi\backends\common\tasklist.py", line 157, in finish
  File "\lib\wubi\backends\common\tasklist.py", line 330, in _notify_listeners
  File "\lib\wubi\backends\common\tasklist.py", line 328, in _notify_listeners
  File "\lib\wubi\frontends\win32\progress_page.py", line 65, in on_progress
  File "\lib\gettext.py", line 412, in ungettext
  File "<string>", line 1, in <lambda>
TypeError: not all arguments converted during string formatting
```
So it was not as difficult to get the reason for the error. 

In the past, I noticed that the existing ngettext for plural forms did not work. Finally, I enabled it with [7f499dc](https://github.com/hakuna-m/wubiuefi/commit/7f499dca9a928397d6244381106129d9c35c0607) and it seemed to work without changing the existing ngettext line for the text "Remaining time approximately".

The problem was that ngettext tried to evaluate the correct plural form a variable string which depends on locale settings. Additionally, some languages have complex arithmetic rules which does not work for all possible string values.

So I added a second return value which is always numeric and does not depend on locale settings.

**Comment by hakuna-m** [comment] 2017-11-01 17:20
Because there hasn't been new bugs reported, I changed the label for [1710r327](https://github.com/hakuna-m/wubiuefi/releases/tag/1710r327) from pre-release to release and I close the issue. If you get that issue again, please reopen it.

**Closed by hakuna-m** 2017-11-01 17:20 UTC
Labels: bug

**Comment by AlekseySyryh** [comment] 2017-11-01 18:03
It works. Thank you.
